name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd frontend && npm ci && npm run build
        env:
          CI: false
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_INTERVIEW_ASSIGNMENT_306921 }}'
          channelId: live
          projectId: interview-assignment-306921
          entryPoint: "./frontend"
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
